services:
  - type: web
    name: wattwitness-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: info
      - key: API_V1_STR
        value: /api/v1
      - key: PROJECT_NAME
        value: WattWitness
      - key: FRONTEND_URL
        value: https://wattwitness-frontend.vercel.app
      - key: ALLOWED_ORIGINS
        value: https://wattwitness-frontend.vercel.app,https://wattwitness-backend.onrender.com
      # Add these environment variables in Render dashboard:
      # DATABASE_URL: your-postgresql-connection-string
      # SECRET_KEY: your-secret-key-here
      # CHAIN_RPC_URL: your-blockchain-rpc-url
      # CONTRACT_ADDRESS: your-contract-address 